### ISSUE TITLE
echo command output nothing in i.MX8M Mini kernel which loaded by uuu

### ISSUE THREAD

**Issue by 115606666** [NXPmicro/mfgtools#135]
We try to echo something under i.MX8M Mini EVK Linux kernel which loaded by uuu, but output nothing.
https://community.nxp.com/thread/513470

**Comment by nxpfrankli** [comment]
Did you use -v option?  

uuu will capture command's output to uuu console. but only -v option show it.

**Comment by 115606666** [comment]
Command echo does output in uuu console running with option -v.
