### ISSUE TITLE
nand_burn_loader.lst invokes "nandbcb init" command which does not exist

### ISSUE THREAD

**Issue by mikecrowe** [NXPmicro/mfgtools#145]
https://source.codeaurora.org/external/imx/uboot-imx/log/?h=imx_v2019.04_4.19.35_1.1.0 contains support for the `nandbcb` command, but not the `nandbcb init` command that `nand_burn_loader.lst` is invoking.

Is support for `nandbcb init` missing from U-Boot, or should `nand_burn_loader.lst` be using `nandbcb update` or some other `nandbcb` command?

**Comment by nxpfrankli** [comment]
2020 Q1 release should include this change
