### ISSUE TITLE
[Question] How many devices can flash at the same time using UUU?

### ISSUE THREAD

**Issue by ajithpv** [NXPmicro/mfgtools#151]
Hi,
I have a use case where multiple devices need to be flashed from a single PC at the same time. I know the older MFG tool supports multi-device flashing up to 4 devices.
I saw UUU support this feature, however, I couldn't find how many devices UUU supports under multi-device flashing.

May I know how many devices I can connect and flash together using the UUU tool? Also, would like to know how to enable multi-device flashing from a single PC?

**Comment by nxpfrankli** [comment]
uuu have not limitation. 
but 815 ROM only support 3 devices per host. 
other chip have not such limitation.
