### ISSUE TITLE
FB: unrecognized command

### ISSUE THREAD

**Issue by StehleJochen** [NXPmicro/mfgtools#156]
my imx6ul device is running u-boot. i have entered "fastboot usb 0". if use uuu -lsusb i can see my device with pid: 0xa4a5 and vid:0x0525. But every "FB: ucmd XXX" command answers Error: unrecognized command.

**Comment by nxpfrankli** [comment]
which version uboot do you use? can you try to run 

uuu -v -b sd uboot.imx?

**Comment by StehleJochen** [comment]
Hello,
the u-boot version is 2018-11. It is a board with eMMC so i tried your command with emmc instead of sd. This is the output:
PS C:\Users\stj\Desktop\UUU> .\uuu.exe -v -b emmc .\u-boot.imx
uuu (Universal Update Utility) for nxp imx chips -- libuuu_1.3.102-0-gb078bd0

Build in config:
        Pctl     Chip            Vid     Pid     BcdVersion
        ==================================================
        SDPS:    MX8QXP          0x1fc9  0x012f  [0x0002..0xffff]
        SDPS:    MX8QM           0x1fc9  0x0129  [0x0002..0xffff]
        SDPS:    MX28            0x15a2  0x004f
        SDPS:    MX815           0x1fc9  0x013e
        SDP:     MX7D            0x15a2  0x0076
        SDP:     MX6Q            0x15a2  0x0054
        SDP:     MX6D            0x15a2  0x0061
        SDP:     MX6SL           0x15a2  0x0063
        SDP:     MX6SX           0x15a2  0x0071
        SDP:     MX6UL           0x15a2  0x007d
        SDP:     MX6ULL          0x15a2  0x0080
        SDP:     MX6SLL          0x1fc9  0x0128
        SDP:     MX7ULP          0x1fc9  0x0126
        SDP:     MXRT106X        0x1fc9  0x0135
        SDP:     MX8MM           0x1fc9  0x0134
        SDP:     MX8MQ           0x1fc9  0x012b
        SDPU:    SPL             0x0525  0xb4a4  [0x0000..0x04ff]
        SDPV:    SPL1            0x0525  0xb4a4  [0x0500..0x9998]
        SDPU:    SPL             0x0525  0xb4a4  [0x9999..0x9999]
        FBK:                     0x066f  0x9afe
        FBK:                     0x066f  0x9bff
        FB:                      0x0525  0xa4a5
        FB:                      0x18d1  0x0d02

Run built-in script:

uuu_version 1.2.39

# @.\u-boot.imx            | bootloader
# @.\u-boot.imx   [.\u-boot.imx] | image burn to emmc, default is the same as bootloader

# This command will be run when i.MX6/7 i.MX8MM, i.MX8MQ
SDP: boot -f .\u-boot.imx

# This command will be run when ROM support stream mode
# i.MX8QXP, i.MX8QM
SDPS: boot -f .\u-boot.imx

# These commands will be run when use SPL and will be skipped if no spl
# SDPU will be deprecated. please use SDPV instead of SDPU
# {
SDPU: delay 1000
SDPU: write -f .\u-boot.imx -offset 0x57c00
SDPU: jump
# }

# These commands will be run when use SPL and will be skipped if no spl
# if (SPL support SDPV)
# {
SDPV: delay 1000
SDPV: write -f .\u-boot.imx -skipspl
SDPV: jump
# }

FB: ucmd setenv fastboot_dev mmc
FB: ucmd setenv mmcdev ${emmc_dev}
FB: ucmd mmc dev ${emmc_dev}
FB: flash bootloader .\u-boot.imx
FB: ucmd if env exists emmc_ack; then ; else setenv emmc_ack 0; fi;
FB: ucmd mmc partconf ${emmc_dev} ${emmc_ack} 1 0
FB: Done


Wait for Known USB Device Appear...
New USB Device Attached at 1:9772
1:9772>Start Cmd:SDP: boot -f .\u-boot.imx
6400%1:9772>Okay (3.114s)
New USB Device Attached at 1:9772
1:9772>Start Cmd:SDP: boot -f .\u-boot.imx
6400%1:9772>Okay (2.454s)



PS C:\Users\stj\Desktop\UUU> .\uuu.exe -v -b emmc .\u-boot.imx
uuu (Universal Update Utility) for nxp imx chips -- libuuu_1.3.102-0-gb078bd0

Build in config:
        Pctl     Chip            Vid     Pid     BcdVersion
        ==================================================
        SDPS:    MX8QXP          0x1fc9  0x012f  [0x0002..0xffff]
        SDPS:    MX8QM           0x1fc9  0x0129  [0x0002..0xffff]
        SDPS:    MX28            0x15a2  0x004f
        SDPS:    MX815           0x1fc9  0x013e
        SDP:     MX7D            0x15a2  0x0076
        SDP:     MX6Q            0x15a2  0x0054
        SDP:     MX6D            0x15a2  0x0061
        SDP:     MX6SL           0x15a2  0x0063
        SDP:     MX6SX           0x15a2  0x0071
        SDP:     MX6UL           0x15a2  0x007d
        SDP:     MX6ULL          0x15a2  0x0080
        SDP:     MX6SLL          0x1fc9  0x0128
        SDP:     MX7ULP          0x1fc9  0x0126
        SDP:     MXRT106X        0x1fc9  0x0135
        SDP:     MX8MM           0x1fc9  0x0134
        SDP:     MX8MQ           0x1fc9  0x012b
        SDPU:    SPL             0x0525  0xb4a4  [0x0000..0x04ff]
        SDPV:    SPL1            0x0525  0xb4a4  [0x0500..0x9998]
        SDPU:    SPL             0x0525  0xb4a4  [0x9999..0x9999]
        FBK:                     0x066f  0x9afe
        FBK:                     0x066f  0x9bff
        FB:                      0x0525  0xa4a5
        FB:                      0x18d1  0x0d02

Run built-in script:

uuu_version 1.2.39

# @.\u-boot.imx            | bootloader
# @.\u-boot.imx   [.\u-boot.imx] | image burn to emmc, default is the same as bootloader

# This command will be run when i.MX6/7 i.MX8MM, i.MX8MQ
SDP: boot -f .\u-boot.imx

# This command will be run when ROM support stream mode
# i.MX8QXP, i.MX8QM
SDPS: boot -f .\u-boot.imx

# These commands will be run when use SPL and will be skipped if no spl
# SDPU will be deprecated. please use SDPV instead of SDPU
# {
SDPU: delay 1000
SDPU: write -f .\u-boot.imx -offset 0x57c00
SDPU: jump
# }

# These commands will be run when use SPL and will be skipped if no spl
# if (SPL support SDPV)
# {
SDPV: delay 1000
SDPV: write -f .\u-boot.imx -skipspl
SDPV: jump
# }

FB: ucmd setenv fastboot_dev mmc
FB: ucmd setenv mmcdev ${emmc_dev}
FB: ucmd mmc dev ${emmc_dev}
FB: flash bootloader .\u-boot.imx
FB: ucmd if env exists emmc_ack; then ; else setenv emmc_ack 0; fi;
FB: ucmd mmc partconf ${emmc_dev} ${emmc_ack} 1 0
FB: Done


Wait for Known USB Device Appear...
New USB Device Attached at 1:9772
1:9772>Start Cmd:SDP: boot -f .\u-boot.imx
6400%1:9772>Okay (2.451s)

**Comment by nxpfrankli** [comment]
your uboot is too old.  ucmd extend have not enabled.
Can you try 2019 uboot?

**Comment by StehleJochen** [comment]
Hi nxpfrankli,

we have the same problem with 2019.10

**Comment by nxpfrankli** [comment]
Does your uboot enable CONFIG_FASTBOOT_UUU_SUPPORT

**Comment by StehleJochen** [comment]
No cant find this this option. Which git repo does it include? we dont want to use yocto

**Comment by nxpfrankli** [comment]
uboot

**Comment by StehleJochen** [comment]
sure in uboot. But for example in mainline u-boot (https://gitlab.denx.de/u-boot/u-boot) the option CONFIG_FASTBOOT_UUU_SUPPORT isn´t available. So which base of u-boot do you take?

**Comment by nxpfrankli** [comment]
this part still not upstreamed. you should nxp uboot repo.
https://source.codeaurora.org/external/imx/uboot-imx

**Comment by StehleJochen** [comment]
thx
