### ISSUE TITLE
Possible high memory usage when flashing

### ISSUE THREAD

**Issue by denravonska** [NXPmicro/mfgtools#165]
I'm trying to use a Raspberry Pi 3 (1GB RAM) as a flash device in a pipeline. When flashing an image I can see that the memory usage skyrockets from 140MB to 1GB RAM plus 1GB swap, and the system becomes unresponsive.

Before venturing further down the rabbit hole to determine if the fault is in uuu or the Azure build agent, does uuu unpack the provided zip to RAM in one swoop or does it unpack on the fly as needed while streaming from disk?

**Comment by nxpfrankli** [comment]
Yes,  uuu design run at 64bit PC, which have enough memory. If run at PI, I suggest you uncompressed zip before run uuu. 

if uuu access regular file,  uuu use mmap, only use bit virtual memory, which is not problem in 64bit system

**Comment by denravonska** [comment]
Closing this as it's by design.

When discarding the output of `uuu` in the Azure pipeline the flash procedure completes just fine.
