### ISSUE TITLE
"Config Config::find(const string &protocal)" not doing what it should?

### ISSUE THREAD

**Issue by markuspg** [NXPmicro/mfgtools#175]
Hi,

looking at the code of "Config Config::find(const string &protocal)" I guess the author intended to have a Config instance returned that only contains ConfigItem of the given protocol. But because of Config's default constructor I'd guess that instead a Config instance is returned which contains all ConfigItem instances of the given protocol twice.

**Comment by nxpfrankli** [comment]
Script support "CFG" dynamic protocol with customized PID VID.  It copy to new object configs in case user change scripts file in daemon mode.  A thread load new scripts, but still a thread running with old scripts.

**Comment by nxpfrankli** [comment]
No update for more than 3 weeks.  feel free to reopen it if still problem
