### ISSUE TITLE
Is it possible flash root.tar.xz file to emmc via uuu

### ISSUE THREAD

**Issue by pingwuu** [NXPmicro/mfgtools#191]
Hi,
We can flash root.tar.bz2 to emm via uuuc, but when I flash a root.tar.xz to emmc, it is not success.
So it is possilbe flash root.tar.xz file to emmc via uuu thanks.

**Comment by jordonwu** [comment]
> are you use linux kernel to burn root.tar.bz2?
yes,  I using kernel to burn root.tar.bz2 is ok, but burn root.**tar.xz** is failed.
I attached my script
[example_kernel_emmc - Copy.zip](https://github.com/NXPmicro/mfgtools/files/4762394/example_kernel_emmc.-.Copy.zip)

Thanks.

**Comment by pingwuu** [comment]
are you use linux kernel to burn root.tar.bz2?
yes, I using kernel to burn root.tar.bz2 is ok, but burn root.tar.xz is failed.
I attached my script
Thanks.
[example_kernel_emmc - Copy.zip](https://github.com/NXPmicro/mfgtools/files/4762405/example_kernel_emmc.-.Copy.zip)

**Comment by nxpfrankli** [comment]
you build initramfs by yourself to add xz support.

**Comment by pingwuu** [comment]
Get it, I will try later, thanks.
