### ISSUE TITLE
"FB:< echo ucmd print"  Example description and successful use?

### ISSUE THREAD

**Issue by flobro30101** [NXPmicro/mfgtools#193]
Has anyone successfully used the shell command? 
I added  simple "FB:< echo ucmd printenv serial#" 

and I get:
1:2>Start Cmd:FB: ucmd printenv serial#
New USB Device Attached at 1:2
1:2>Fail Failure claim interface(0.201s)
1:2>Fail Failure claim interface(0.201s)

Am I missing something?

I would like to use this to get info so I can generate a MAC address for my boards.

Thanks

**Comment by nxpfrankli** [comment]
run at windows or linux?
is it success if direct use 
FB: ucmd printenv serial#

**Comment by flobro30101** [comment]
Sorry, it is running on Linux but not working...

**Comment by flobro30101** [comment]
Also, everything else works in my scripts...

**Comment by nxpfrankli** [comment]
I duplicate your problem. let me try to fix it

**Comment by flobro30101** [comment]
Amazing speed.. It works as advertised.

Thanks

**Comment by nxpfrankli** [comment]
Can you try https://ci.appveyor.com/project/nxpfrankli/mfgtools-kvqcg/builds/33490219/job/43lwh43mq1dwea6q/artifacts?

**Comment by flobro30101** [comment]
I pulled the latest git changes and they worked.
Thanks

Floyd Brown
