### ISSUE TITLE
Bulk(R):LIBUSB_ERROR_TIMEOUT

### ISSUE THREAD

**Issue by scooty334** [NXPmicro/mfgtools#196]
Hi guys, im experiencing an issue when i try to download to my i.MX6ULL (NAND) custom board.

zimage, u-boot.imx, imx6ull.dtb, fsl-image-mfgtool-initramfs-imx_mfgtools.cpio.gz.u-boot, works smooth but when it goes to rootfs im getting this error under windows 10 and ubuntu 20.04 also. im using kernel version 4.19.128 if that is matter. 

1:10    21/24 [Bulk(R):LIBUSB_ERROR_TIMEOUT          ] FBK: ucp rootfs.tar t:-

this happens when trying to load rootfs.tar and disconnects at 14%. 

Here is the script: 

=====================================================
FBK: ucmd source /tmp/mtd.sh; flash_erase /dev/mtd${nandrootfs} 0 0
FBK: ucmd source /tmp/mtd.sh; ubiattach /dev/ubi_ctrl -m ${nandrootfs}
FBK: ucmd source /tmp/mtd.sh; ubimkvol /dev/ubi0 -Nnandrootfs -m
FBK: ucmd source /tmp/mtd.sh; mkdir -p /mnt/mtd
FBK: ucmd source /tmp/mtd.sh; mount -t ubifs ubi0:nandrootfs /mnt/mtd

FBK: acmd export EXTRACT_UNSAFE_SYMLINKS=1; tar -xv -C /mnt/mtd
FBK: ucp rootfs.tar t:-
FBK: sync
FBK: ucmd umount /mnt/mtd

FBK: done

====================================================

How can i fix this issue ? 

[debug log you can find it here](https://github.com/NXPmicro/mfgtools/files/4843149/debug.log)

(also mfgtools v2.7 worked before with lower kernel version on a same custom hardware as i using now.)
so hardware malfunction is out of picture.  

Thanks

**Comment by nxpfrankli** [comment]
It may out of memory,  nand driver get null point from kmalloc and missed a safty check. 

This problem need 5.4 kernel usb driver upgrade, which support scatter list. 

uuu switch to use ffs.

**Comment by nxpfrankli** [comment]
if still have problem, please reopen.
