### ISSUE TITLE
UUU and USB cable length

### ISSUE THREAD

**Issue by ajithpv** [NXPmicro/mfgtools#205]
Hi,

I would like to know, whether UUU impose any restriction on the length of the USB cable?

I'm using i.MX8QXP custom board with UUU version(libuuu) 1.3.102 on Windows Host PC.
We have observed a case where the USB got detected while starting the flashing (i.MX8QXP based custom platform) however, were not flashing and throws "LIBUSB_ERROR_PIPE" at the beginning itself. When the USB cable length got reduced to half, then the flashing completed successfully without any issues!

Hence, Is there any limit for the USB cable (say, maximum length of the USB cable should be 1 meter for reliable flashing) from the UUU/libusb software point of view? 
Also, Please let me know anyone tested the UUU with 3 meter or 5 meter (or even more) USB cable.

**Comment by nxpfrankli** [comment]
This is related usb signal quality. I am NOT expert at this area. It is also depend on board design.  Our boards pass usb ceritification. It should work with cerified USB Cable.  

Our test team genenall use 1-2m cable.
