### ISSUE TITLE
 flash -raw2sparse

### ISSUE THREAD

**Issue by bevincb** [NXPmicro/mfgtools#213]
Please let us know the use of "-raw2sparse" option in flash command of uuu tool.

Example:
FB: flash -raw2sparse all k-base-image-ma035-01.wic.bz2\\*

Can you please help us to understand what will happen on execution of the above command.

**Comment by nxpfrankli** [comment]
uboot only accept android sparse file format for **all** partion. -raw2sparse means convert binary raw file into sparse format run time.

**Comment by nxpfrankli** [comment]
if still have problem, please reopen.

**Comment by nxpfrankli** [comment]
How much reduced?  raw2spare using the simple method.  In our release built image, there are few sparse area exist. especially using zstd or other compress method.  Sparse information may lost during compression.
