### ISSUE TITLE
Possibility of "if else" check inside UUU script

### ISSUE THREAD

**Issue by ajithpv** [NXPmicro/mfgtools#215]
Hi,

I would like to know whether UUU script supports check cases (such as if..else...) before doing some operations?
Example:
**if** (register value == empty)
**then** write the new value
**else** don't write the new value

How we can validate a specific action (based on some conditions) before executing in UUU script?
Looking forward to get some idea or suggestions here.

**Comment by nxpfrankli** [comment]
if you use FB, suggest use uboot if else command

``
FB: ucmd if env exists nandfit_part; then nand erase.part nandfit; nand write ${fastboot_buffer} nandfit ${fastboot_bytes}; else true; fi;
``

if you use FBK, suggest use shell's if else command
