### ISSUE TITLE
Is there a plan to add GUI of uuu?

### ISSUE THREAD

**Issue by keelung-yang** [NXPmicro/mfgtools#220]
Since console is not friendly then GUI to end users.

**Comment by nxpfrankli** [comment]
Currently it is not easy to implement GUI cross platform and less dependence.  And burning process is too flexiable. 

Many system need use it to do auto deloy. 

So currently, no plan to support GUI. 

uuu actually seperate logic code and ui code. If anyone want, they can build their UI easily.

**Comment by nxpfrankli** [comment]
if still have problem, please reopen.
