### ISSUE TITLE
FBK and imx-uuu

### ISSUE THREAD

**Issue by ole00** [NXPmicro/mfgtools#224]
The PDF documentation mentions FBK protocol implemented in project imx-uuu. 

Here is the quote from the documentation:
"FBK: Android fastboot protocol, implement at initramfs. See project imx-uuu"

I can't find the project sources. Could you please publish a link to the source code/project of imx-uuu?

I assume the implementation ox imx-uuu is a software that resides in initramfs, and is able to execute remote commands sent over USB by another PC utilising uuu tool. Is that correct? 
Thank you.

**Comment by nxpfrankli** [comment]
yes, https://github.com/NXPmicro/imx-uuc

**Comment by nxpfrankli** [comment]
typo fixed and added link
https://github.com/NXPmicro/mfgtools/wiki/UUU-default-support-protocol-list

**Comment by ole00** [comment]
Thank you for the links.
