### ISSUE TITLE
imx6ul programming issue on Linux and Win10

### ISSUE THREAD

**Issue by beb1983** [NXPmicro/mfgtools#225]
Hi all,
we have some problems with uuu that it shows no errors and no problems but the device which is recognized correctly won't boot. With the same binary and bootloader binary on another system it is just working correctly.

I see only one difference between working and none working is that when it is flashing I see a slower progress.

This problem occurs first on Win10 but later in Linux too. 

I'm running Ubuntu LTS18.04 and there it is running fine. On the company notebook with Win10 it is not running. With my win10 vm it is working too. With another linux vm (I tested Debian, ubuntu server and desktop 20.04) it is just not working.

Let me know what output you need. The problem is that the uuu output is everytime fine so there is no difference in the output. After I flashed it on a system which isn't working the device is in a unknown state. If I start the programming again is shows a libusb_timeout_error. The device is recognized correctly on all systems. I execute uuu with sudo permissions.

I even compiled it from source on all linux systems and is just don't work. We need this tool for our production, so I hope you can help me with this issue.

Here are the output with the different timings.
This is working:
1:5>Start Cmd:SDP: boot -f "barebox.img"
6400%1:5>Okay (0.166s)
1:5>Start Cmd:SDP: done
1:5>Okay (0s)

This is not working:
1:1>Start Cmd:SDP: boot -f "barebox.img"
6400%1:5>Okay (4.255s)
1:1>Start Cmd:SDP: done
1:1>Okay (0s)

Thanks in advance.

Regards,
Benjamin

**Comment by nxpfrankli** [comment]
It is most likely that your board DDR is not stable or barebox.img have random problem.

SDP already download image and jump, ROM already jump into your image.
