### ISSUE TITLE
u-boot.imx not starting with uuu but stating with imx_usb_loader

### ISSUE THREAD

**Issue by ddvk** [NXPmicro/mfgtools#230]
I have a u-boot.imx:
Image Type:   Freescale IMX Boot Image
Image Ver:    2 (i.MX53/6/7 compatible)
Mode:         PLUGIN
Plugin Data Size:     65536 Bytes = 64.00 KiB = 0.06 MiB
Plugin Code Size:     0 Bytes = 0.00 KiB = 0.00 MiB
Plugin Load Address:  00910000
Plugin Entry Point:   0091042c
U-Boot Data Size:     65536 Bytes = 64.00 KiB = 0.06 MiB
U-Boot Load Address:  00910000
U-Boot Entry Point:   0091042c

uuu -f u-boot.imx says ok, but the device does not boot.

The device:
DEVICE: SE Blank ULT1 (0x15A2, 0x0076)

 ---------------------------------------------------------
 Connected Device Info
 ---------------------------------------------------------

 Device:        iMX7 Solo/Dual
 Silicon Rev:   1.3

 iROM Release:  01.00.05
 iROM Version:  0x12

 WDOG State:    Disabled

 SBMR1: 0x00002820
   BOOT_CFG_1  = 0x20
   BOOT_CFG_2  = 0x28
   BOOT_CFG_3  = 0x00
   BOOT_CFG_4  = 0x00

 SBMR2: 0x00000011
   BMOD        = 00     Boot from Fuses
   BT_FUSE_SEL = 1
   DIR_BT_DIS  = 0
   SEC_CONFIG  = 01

 PersistReg Val: 0x00000000
 ANALOG DIGPROG: 0x00720013

imx_usb_loader
succeeded (security 0x56787856, status 0x88888888)
jumping to 0x00910400
failed (security 0x56787856, status 0x33220a00)
HAB security state: development mode (0x56787856)
== work item
filename u-boot.imx
load_size 0 bytes
load_addr 0x00000000
dcd 0                                                          a
clear_dcd 0
plug 0
jump_mode 3
jump_addr 0x00000000
== end work item
header_max=10400

loading binary file(u-boot.imx)  to 877effd4, skip=0, fsize=9f02c type=aa                       r
                                                                
<<<651308, 651308 bytes>>>                                     s
succeeded (security 0x56787856, status 0x88888888)
jumping to 0x877f08e4

Any advice?

**Comment by OsterlaD** [comment]
See !235 , you need a special image with an additional region signed.

If you have a not yet closed device, you should see an error message with the details.

**Comment by ddvk** [comment]
thank!
