### ISSUE TITLE
UUU tool only working when the files in same directory

### ISSUE THREAD

**Issue by danie007** [NXPmicro/mfgtools#237]
Hi,

When I try to run the UUU tool with `lst` file pointing to different location for `u-boot` and `image`.
I've given full paths for the files:
 ```
uuu (Universal Update Utility) for nxp imx chips -- libuuu_1.4.43-9-gb1d7956

Wait for Known USB Device Appear...
Error: fail open file: >/home/ux/Documents/cst_test//home/ux/Documents/cst_test/cst_encrypt_sign/tmp/u-boot.imx
```

As you can see `/home/ux/Documents/cst_test//home/ux/Documents/cst_test/cst_encrypt_sign/tmp/u-boot.imx` here `UUU` tool appends the current directory to the file location.

**NOTE**: It's working fine if all the files are in same `dir` or when we give the relative paths. I'm using script to automate `UUU` so it'll be easier if I can give the full paths.

**Comment by danie007** [comment]
TODO: Try this suggested solution: https://github.com/NXPmicro/mfgtools/issues/236#issuecomment-727139060

**Comment by nxpfrankli** [comment]
Can you add ">" before your full path in lst.  >/home/ux/Documents/cst_test//home/ux/Documents/cst_test/cst_encrypt_sign/tmp/u-boot.imx

**Comment by danie007** [comment]
@nxpfrankli Thanks for the solution. It's working now.
