### ISSUE TITLE
How to add delay for FBK command?

### ISSUE THREAD

**Issue by ajithpv** [NXPmicro/mfgtools#238]
Hi,

I would like to know, how we can add delay for the FBK command.

So far, I understood how to add delay for initial timeout (using -t) and FB delay (using -t with FB command).

However, I didn't find how to add delay for FBK command.

**Comment by nxpfrankli** [comment]
Do you means timeout? 

FBK needn't timeout because linux can return busy status every second.  uboot is single thread and can't return busy status when running a command.

**Comment by ajithpv** [comment]
Thank you @nxpfrankli for your response.

Does this means timeout is not required for FBK? 

Also, what is the default timeout time for FBK and FB (if we didn't specify the -t with FB)?

**Comment by nxpfrankli** [comment]
FBK and FB default value is 2s.
