### ISSUE TITLE
UUU built on Windows 10 not working outside build dir

### ISSUE THREAD

**Issue by danie007** [NXPmicro/mfgtools#245]
Hi @nxpfrankli 

I've tried building `uuu` on Windows and this gives me the following error whenever, I try running outside the build directory. 
![image](https://user-images.githubusercontent.com/50566479/102750911-c1276900-438c-11eb-8900-3e45845c2dd0.png)

It would be helpful if you could point me out how to attach the `libusb.dll`(*it present in build folder*) into the `uuu.exe`

Thanks in advance.

**Comment by nxpfrankli** [comment]
Please use uuu_static.sln

**Comment by danie007** [comment]
Hi @nxpfrankli 

Thanks for pointing out our mistake, after building `uuu` with [uuu-static-link.sln](https://github.com/NXPmicro/mfgtools/blob/master/msvc/uuu-static-link.sln) everything work as intended.

CC @tkmozhi
