### ISSUE TITLE
 Relation between UUU2 flashing and Windows OS performance #270

### ISSUE THREAD

**Issue by rajumallah** [NXPmicro/mfgtools#291]
Hi All,

https://github.com/NXPmicro/mfgtools/issues/270

Continuing to above issue, 

Can you please provide a list of VID used for Ublox which need to be added in ignored list because we are seeing in registry that there are several other VIDs are registered. it is difficult to search for Ublox id.

Since with every device getting connected to PC registry is growing and it is causing system degradation.
Generally size of registry file is around ~400MB for production pc, but after production of several hundreds of devices connected to USB of pc, its size grown upto 1.5 GB.

Thanks,
Raju Mallah

**Comment by nxpfrankli** [comment]
run cmd 
uuu -IgSerNum

**Comment by nxpfrankli** [comment]
no feedback over month. if still problem, please reopen
