### ISSUE TITLE
NXP 8MPLUS-BB not detected by UUU utility

### ISSUE THREAD

**Issue by lyah** [NXPmicro/mfgtools#293]
UUU can't detect NXP 8MPLUS-BB.   NXP 8MPLUS-BB board IDs are: VID = 0x0403, PID = 0x6011. This board is not supported in https://github.com/NXPmicro/mfgtools/releases/tag/uuu_1.4.139    config.cpp.

**Comment by nxpfrankli** [comment]
No feedback over one month. Still have problem, please reopen
