### ISSUE TITLE
liberror.h is not thread-safe

### ISSUE THREAD

**Issue by wf-** [NXPmicro/mfgtools#335]
Got bit by this while flashing two devices in parallel, with main culprit being the set_last_err_string() function. Caused various heap corruptions at the end of flashing process.

I resolved this by protecting the uuu_get_last_err_string() and set_last_err_string() functions with mutex.

**Comment by nxpfrankli** [comment]
Do you have pull request?

**Comment by wf-** [comment]
For a good measure i've also wrapped `g_last_err_id` in `std::atomic`

**Comment by nxpfrankli** [comment]
Pull request merged
