### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by gruizdigi** [NXPmicro/mfgtools#338]
Hi @nxpfrankli ,

We are soon to do a release that requires one of the latest changes in UUU. I have already a working, manually built, UUU binary but I was wondering if you have an approximate date for the next release in this repo?

Thanks in advance.

**Comment by nxpfrankli** [comment]
Which one do you need?  1.5.4?

**Comment by gruizdigi** [comment]
The one we need is at least 1.5.6.

**Comment by nxpfrankli** [comment]
I create a pre release https://github.com/NXPmicro/mfgtools/releases/tag/uuu_1.5.11

I will remove pre-release take after some month.

**Comment by gruizdigi** [comment]
Many thanks @nxpfrankli .

When you remove the pre-release, will there be an official release to replace it?

**Comment by nxpfrankli** [comment]
If not problem, I just remove pre-release tag and update release notes.  
If there are problem, new pre-release will be created.

**Comment by gruizdigi** [comment]
Great, that will work fine for us. Thank you!
