### ISSUE TITLE
Is the license the CPOL or BSD-3c?

### ISSUE THREAD

**Issue by fhunleth** [NXPmicro/mfgtools#5]
The `LICENSE` file and several header files have the BSD license text, but `CPOL.htm` also exists. Was `CPOL.htm` committed by mistake?

**Comment by nxpfrankli** [comment]
There are some files which is CPOL.   Most part is BSD.

**Comment by fhunleth** [comment]
Would it be possible for you to add a short section to the README to explain what's covered by which license? Fwiw, I couldn't find any files with references to the CPOL.

Also, I noticed that when I switched to the `windows` branch, the `LICENSE` file was removed and replaced by a `COPYING.MIT`. Could you clarify what's covered by the MIT license?

**Comment by nxpfrankli** [comment]
I update master (linux) branch. 
Windows branch need check history.

**Comment by fhunleth** [comment]
Thanks!

**Comment by nxpfrankli** [comment]
COPYING.MIT already removed
