### ISSUE TITLE
Known issue: UUU does not work on linux for imx8M Mini (early board version)

### ISSUE THREAD

**Issue by angolini** [NXPmicro/mfgtools#54]
Please document that in early imx8MMini boards there is a bug in the rom that prevents linux from registering the HID device.

This is already fixed and is going to be applied on any new rom.

**Comment by nxpfrankli** [comment]
https://github.com/NXPmicro/mfgtools/wiki/Release-Notes

**Comment by angolini** [comment]
I think that's enough. Thanks a lot!
