### ISSUE TITLE
How to use uuu when my pc link with more than one boards?

### ISSUE THREAD

**Issue by atline** [NXPmicro/mfgtools#59]
@nxpfrankli If use fastboot for android, I have `-s <specific device>    specify device serial number` to find one board & do my command on the specified board.

If this feature supported in uuu? I did not find any clear example about this, please suggest.

**Comment by nxpfrankli** [comment]
No

**Comment by nxpfrankli** [comment]
If you use the same type boards,  uuu -d to support multi boards.  if not same boards, you can use -m port number to identify a special boards

**Comment by nxpfrankli** [comment]
No response move than 20 days. If still issue, please reopen it.

**Comment by rubenmoral** [comment]
@nxpfrankli if I have multiple boards connected to my PC, how can I find out the specific port number of one of them? Is there any command that lists the available boards?

**Comment by nxpfrankli** [comment]
no such command,  work around as
uuu fb: delay 10000

**Comment by rubenmoral** [comment]
That command only shows the port number of the second board. In addition, in order to run the command, the boards must be in fastboot mode, which in some cases may not be possible if one of them does not have uboot programmed.
```
uuu (Universal Update Utility) for nxp imx chips -- libuuu_1.2.135-0-gacaf035

Success 0    Failure 0

         1/ 0 [                                      ]
1:4143   1/ 0 [                                      ]

Okay
```
Where does uuu get the port identifier from?

**Comment by nxpfrankli** [comment]
try uuu sdp: delay 10000
uuu sdps: delay 1000, 

I will add command to list in future

**Comment by nxpfrankli** [comment]
https://github.com/NXPmicro/mfgtools/commit/302da9151a95fb7ff3b61281a9a6aee4c6d4e3f8

-lsusb option added

**Comment by rubenmoral** [comment]
Wow, that's great! Thank you very much!

**Comment by npeters2** [comment]
Apologies for opening an old thread, but it seemed very related. To clarify, if I have 2 of the same device, can I program them separately, but simultaneously (with some overlap) from individual command prompts using "uuu -d -m 1:1" from one prompt and "uuu -d -m 1:2" from another? We tried using just the -m parameters with the paths this way, but ran into some issues (didn't include the -d parameter). Reading the documentation, I couldn't tell if -m just specified to monitor a given path, but then still attempt to program all of the connected devices or not. Any help is greatly appreciated!

**Comment by nxpfrankli** [comment]
-m just program the device, which connected the specific port.

**Comment by npeters2** [comment]
Thanks. This worked when I tried it myself. I think the other individual I am working with may be experiencing a different issue. I will open a separate ticket if we are unable to resolve.
