### ISSUE TITLE
imx8mmevk libusb error timeout

### ISSUE THREAD

**Issue by austinf** [NXPmicro/mfgtools#62]
When trying to load code onto sd card on the imx8mmevk board, with the following command:

`sudo ./uuu/uuu -b sd_all ~/imx-boot-imx8mmevk-sd.bin ~/core-image-minimal-imx8mmevk.sdcard
`
I get:
```
uuu (Universal Update Utility) for nxp imx chips -- libuuu_1.1.87-3-g9d88a8c

Success 0    Failure 1

1:1    1/ 1   [HID(W):LIBUSB_ERROR_TIMEOUT ] SDP: boot -f /home/austinf/imx-boot-imx8mmevk-sd.bin
```

Not sure how to debug what's going wrong further.

**Comment by lznuaa** [comment]
The early imx8m chip need apply a ROM patch.   windows system have not such problem.

**Comment by austinf** [comment]
My only windows system is 32 bit, can 32 bit windows binaries be provided? The ones on the release page appear to be 64 bit only.

Building from source on windows requires quite a bit of environment setup it looks like.

**Comment by nxpfrankli** [comment]
We don't prefer use 32bit system, because it will be problem when download big files.

**Comment by nxpfrankli** [comment]
did you boot from other boot source? 
check if rom patch locked 
u-boot=> fuse read 0 0

**Comment by austinf** [comment]
I can boot off an sdcard.

u-boot=> fuse read 0 0
Reading bank 0:

Word 0x00000000: b0010103

How do I interpret that result?

**Comment by nxpfrankli** [comment]
this is early chip problem.  Someone report there are not such problem at  ubuntu 18.04
