### ISSUE TITLE
file transfer from target to windows PC

### ISSUE THREAD

**Issue by vmuthusu** [NXPmicro/mfgtools#79]
I run the following command to transfer a file from Target to Host PC running windows
FBK: ucp /tmp/file.txt file.txt
file.txt is successfully transfered to the Host PC. But the content seems to be all zeros.

**Comment by nxpfrankli** [comment]
try prebuild version https://ci.appveyor.com/project/nxpfrankli/mfgtools-kvqcg/builds/21896046/job/bys22yq9cruvu8vu/artifacts

**Comment by vmuthusu** [comment]
Hi Frankli
I am able to transfer file from target to Windows PC without any issues using the above prebuild version.
Thanks for your help.
Can you share the Linux version of this as well?

**Comment by nxpfrankli** [comment]
https://github.com/NXPmicro/mfgtools/releases/tag/uuu_1.2.66
