### ISSUE TITLE
Archlinux 

### ISSUE THREAD

**Issue by leemeng0x61** [NXPmicro/mfgtools#81]
➜  flash sudo uuu -V uuu-dualos-mx8qm-mek-emmc.lst                                                                            18:46:11
uuu (Universal Update Utility) for nxp imx chips -- libuuu_1.2.89-0-gd7d8504

Build in config:
	Pctl	 Chip		 Vid	 Pid	 BcdVersion
	==================================================
	SDPS:	 MX8QXP		 0x1fc9	 0x012f	 [0x0002..0xffff]
	SDPS:	 MX8QM		 0x1fc9	 0x0129	 [0x0002..0xffff]
	SDP:	 MX7D		 0x15a2	 0x0076
	SDP:	 MX6Q		 0x15a2	 0x0054
	SDP:	 MX6D		 0x15a2	 0x0061
	SDP:	 MX6SL		 0x15a2	 0x0063
	SDP:	 MX6SX		 0x15a2	 0x0071
	SDP:	 MX6UL		 0x15a2	 0x007d
	SDP:	 MX6ULL		 0x15a2	 0x0080
	SDP:	 MX6SLL		 0x1fc9	 0x0128
	SDP:	 MX7ULP		 0x1fc9	 0x0126
	SDP:	 MXRT106X	 0x1fc9	 0x0135
	SDP:	 MX8MM		 0x1fc9	 0x0134
	SDP:	 MX8MQ		 0x1fc9	 0x012b
	SDPU:	 SPL		 0x0525	 0xb4a4	 [0x0000..0x04ff]
	SDPV:	 SPL1		 0x0525	 0xb4a4	 [0x0500..0x9998]
	SDPU:	 SPL		 0x0525	 0xb4a4	 [0x9999..0x9999]
	FBK:	 		 0x066f	 0x9afe
	FBK:	 		 0x066f	 0x9bff
	FB:	 		 0x0525	 0xa4a5
	FB:	 		 0x18d1	 0x0d02
Wait for Known USB Device Appear...
>Start Cmd:CFG: FB: -vid 0x1fc9 -pid 0x0129
>Okay
New USB Device Attached at 1:2
1:2>Start Cmd:FB: ucmd setenv fastboot_dev mmc
libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=2
1:2>Fail Bulk(W):LIBUSB_ERROR_IO

**Comment by nxpfrankli** [comment]
Android default script is wrong.

Please remove line
"CFG: FB: -vid 0x1fc9 -pid 0x0129"
