### ISSUE TITLE
unable to flash from low memory host

### ISSUE THREAD

**Issue by Dwaff** [NXPmicro/mfgtools#90]
When trying to flash 3.4 GB image file, the uuu utility aborts with:
Wait for Known USB Device Appear...
Error: fail open file: >devkit.img

And the strace displays:
open("devkit.img", O_RDONLY|O_LARGEFILE) = 3
mmap2(NULL, 3600000000, PROT_READ, MAP_SHARED, 3, 0) = -1 ENOMEM (Cannot allocate memory)

The host is 32bit linux machine, and it will never see that much of memory. It is bigger then available address space.

**Comment by nxpfrankli** [comment]
Yes, 32bit system have such limitation. 
Please use 64bit system.
