### ISSUE TITLE
uuu tool issue - doesnt detect USB device

### ISSUE THREAD

**Issue by Haturi89** [NXPmicro/mfgtools#94]
Hi,
I have a eval kit from NXP MX8QXPMEK. I can boot it with the pre-configured SD-Card without problems. When I doesnt insert the SD-Card board switches to SDP. In my device manager the board is detected. The old MFGTools shows "HID device detected".

Now  I am trying to download the pre-compiled u-boot. When I start the uuu (Version 1.2.91) it shows me the message Wait for Known USB Device Appear... and wait. It look like the USB device (board) is not detected.

How can I solve this?

I am using Windows10 as host system.

regards Haturi

![device-manager](https://user-images.githubusercontent.com/49388046/55703974-5a58f500-59db-11e9-9ce2-fba9472c78a3.png)

![uuu output](https://user-images.githubusercontent.com/49388046/55703962-54fbaa80-59db-11e9-912a-108c10617a78.png)

**Comment by nxpfrankli** [comment]
You are using QXP A0 chip, which is not support by UUU. 
A0 chip is not production chip.

**Comment by Haturi89** [comment]
Okay but there must be a way how to get it to work. I mean we have purchased those CPUs from NXP so we can´t develop if it´s doesnt work. Furthermore we have bought a development kit (i.MX8QXP-MEK) and it also doesnt work with uuu.
So what should I modify to get it to work?

regards,
Haturi

**Comment by nxpfrankli** [comment]
The whole boot flow is changed in QXP B0 totally.  A0 Chip is not production one. If you purchased it, you should contact sale to replace it with B0 chip.

**Comment by Haturi89** [comment]
Okay thanks for the explanation.
